{'label':'Ang Mo Kio',      'value':'ANG'},
{'label':'Bedok',           'value':'BED'},
{'label':'Bishan',          'value':'BIS'},
{'label':'Bukit Batok',     'value':'BUBA'},
{'label':'Bukit Merah',     'value':'BUME'},
{'label':'Bukit Panjang',   'value':'BUPA'},
{'label':'Bukit Timah',     'value':'BUTI'},
{'label':'Central Area',    'value':'CTA'},
{'label':'Choa Chu Kang',   'value':'CCK'},
{'label':'Clementi',        'value':'CLE'},
{'label':'Geylang',         'value':'GLN'},
{'label':'Hougang',         'value':'HOU'},
{'label':'Jurong East',     'value':'JUE'},
{'label':'Jurong West',     'value':'JUW'},
{'label':'Kallang/Whampoa', 'value':'KAL'},
{'label':'Lim Chu Kang',    'value':'LIM'},
{'label':'Marine Parade',   'value':'MRP'},
{'label':'Pasir Ris',       'value':'PAR'},
{'label':'Punggol',         'value':'PUN'},
{'label':'Queenstown',      'value':'QUN'},
{'label':'Sembawang',       'value':'SEM'},
{'label':'Sengkang',        'value':'SEN'},
{'label':'Serangoon',       'value':'SER'},
{'label':'Tampines',        'value':'TAM'},
{'label':'Toa Payoh',       'value':'TOA'},
{'label':'Woodlands',       'value':'WOD'},
{'label':'Yishun',          'value':'YIS'},
